package blizzard

var textureTypeNames = map[uint32]string{
	0:  "None",
	1:  "Skin",
	2:  "ObjectSkin",
	3:  "WeaponBlade",
	4:  "WeaponHandle",
	5:  "Environment",
	6:  "Hair",
	7:  "FacialHair",
	8:  "SkinExtra",
	9:  "UISkin",
	10: "Miscellaneous",
	11: "MonsterSkin1",
	12: "MonsterSkin2",
	13: "MonsterSkin3",
	14: "ItemIcon",
	15: "GuildBGColor",
	16: "GuildEmblemColor",
	17: "GuildBorderColor",
	18: "GuildEmblem",
	19: "Eyes",
	20: "Accessories",
	21: "SecondarySkin",
	22: "SecondaryHair",
	23: "SecondaryArmor",
	24: "Texture24",
	25: "Texture25",
	26: "Texture26",
}
